feat: Mapper and json added
Evgenia-bit/artus pull request #4
Opened 2023-10-16 13:30 UTC by Evgenia-bit

2023-10-16 13:43 UTC, Evgenia-bit commented
Пока что не все блоки преобразуются, на данный момент только параграф, цитата, список, видео и разделитель

2023-10-17 08:22 UTC, mpkander commented
> На данный момент преобразуются только параграф, цитата, список, видео и разделитель

Предлагаю в документации сразу сделать такую структуру: 

```
.
└── docs/
    └── content/
        ├── examples/
        │   ├── full_example.json
        │   ├── parapgraph.json
        │   └── video.json
        └── README.md
```

В README на английском надо описать все типы контента, который мы сейчас обрабатываем. Предлагаю остановиться на: 
- Параграф с rich-текстом (bold, italic, monospaced)
- Заголовок с параметрами уровня 
- Список
- Видео 
- Изображение

2023-10-17 08:30 UTC, mpkander commented
@Evgenia-bit  И давай в README сразу опишем, из чего состоят блоки и каждый отдельный блок, какие параметры обязательные, а какие нет 

У блока должно быть type и data, это обязательные параметры. Я предлагаю ещё сделать параметр "compat" (совместимость). Он будет нужен на случай, если приложение не умеет обрабатывать определённый тип из-за версии, но его всё равно стоит как-то отобразить 

Предлагаю делать это в таком формате: 

```json
{
    "type": "spoiler",
    "data": {
        "text": "something"
    },
    "compat": {
        "type": "paragraph",
        "data": {
            "text": "something"
        }
    }
}
```

2023-10-17 08:40 UTC, mpkander requested changes

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +                            "font_size": 20.0
Давай не делать настолько широкую кастомизацию, font_size пока не нужен

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +                "align": 1,
Не нужна такая кастомизация сейчас, как мне кажется

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +                            "color": "AARRGGBB",
Цвет тоже сейчас предлагаю убрать. Подразумевать, что весь наш текст — монотонный

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +                "type": 0,
А что значит type 0? Давай подробно опишем тип "list" в README

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +            "type": "todo",
Слишком сложно, давай оставим это на вторую итерацию

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +            "type": "link",
Мне кажется, это должно быть частью параграфа

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +            "type": "image",
Тут всё ок, предлагаю оставлять в таком виде

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +            "type": "file",
Давай повременим пока что с файлом?

2023-10-17 08:40 UTC, mpkander commented on docs/data_format.json
> +            "type": "video",
Видео тоже окей, давай оставлять

2023-10-18 11:44 UTC, closed without merging