feat: added json mapping to widgets
Evgenia-bit/artus pull request #7
Opened 2023-10-18 07:58 UTC by Evgenia-bit

2023-10-20 08:46 UTC, mpkander requested changes

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/mapper.dart
> +final mapper = Mapper(blockParser: BlockParser());
Почему это поле здесь и публично?

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/image_block.dart
> +    if (model.url == null) return const SizedBox.shrink();
Плохое решение 

1. Почему вообще URL картинки может быть 0? Тогда нет смысла вообще добавлять виджет в дерево

2. URL должен быть корректным уже когда попадает сюда. То есть на этапе парсинга 

3. Если что-то пойдёт не так и изображение не загрузится или будет ошибка, то нужно сделать стандартный плейс-холдер. Например, серый квадратик с перечёркнутым изображением или что-то вроде этого

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/image_block.dart
> +        model.url!,
Бэнг оператор ненужный, нужно изменить проверку

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/list_block.dart
> +                IconData(0xe163, fontFamily: 'MaterialIcons'),
А почему не через `Icons.something`?

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/paragraph_block.dart
> +              fontFamily: child.style.isMonospaced ? 'RobotoMono' : null,
Название шрифта нужно вынести в общую константу на уровень всего приложения

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/paragraph_block.dart
> +        style: const TextStyle(color: Color(0xFF000000)),
Colors.black

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/blocks/video_block.dart
> +    if (uri == null) return const SizedBox.shrink();
Тут также нужен какой-то плейсхолдер, который объясняет: "На этом месте должно быть видео, но его почему-то тут нету"

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/heading_block_model.dart
> +      : level = safeCast<int>(json?['level']) ?? 1,
Хорошим тоном будет указать в документации к классу или конструктору, что при неудачном парсинге уровня заголовка по умолчанию выставляется самый большой. Кажется, что это правда логично

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/heading_block_model.dart
> +        text = safeCast<String>(json?['text']) ?? '';
А вот если мы не можем нормально спарсить текст, я вообще не вижу смысла что-либо показывать пользователю, только если текст, действительно, не пустой 

Предлагаю на этот случай возвращать объект не типа `CustomHeadingBlockModel`, а типа 'FailedBlockModel', чтобы мы при построении интерфейса игнорировали его полностью. Но могли при этом, например, записать в лог, что у нас была ошибка и мы не смогли спарсить такое

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/image_block_model.dart
> +  abstract final String? url;
Почему может быть null? Мне кажется, возвращать картинку нет никакого смысла, если тут может быть null

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/list_block_model.dart
> +  abstract final bool isOrdered;
Избавляйся от мышления построения функциональности через булевы выражения. Тут должны быть классы-наследники: OrderedListBlockModel и BulletedListBlockModel 

Булевы выражения в данном случае просто нерасширяемы

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/paragraph_block_model.dart
> +      : text = safeCast<String>(json['text']) ?? '',
Кажется, если мы в параграфе не смогли хотя бы один кусочек текста спарсить, нужно фейлить весь параграф и возвращать ничего

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/models/video_block_model.dart
> +  abstract final String? url;
Аналогично с изображением. Не вижу смысла url делать нулевым

2023-10-20 08:46 UTC, mpkander commented on packages/mapper/lib/src/utils/safe_cast.dart
> +// ignore: type_annotate_public_apis
Предпочитай убирать в конфигурации правила, нежели игнорировать их

2023-10-24 07:45 UTC, mpkander requested changes

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/widgets/list.dart
> +  final Widget Function(int) buildMarker;
Предпочитай добавлять контекст в билдеры

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/block_parser.dart
> +    if (blocks == null) return [];
Лучше выбрасывать Exception о том, что формат данных неправильный

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/block_parser.dart
> +final typeMap = {
Почему он публичный?

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/image_block.dart
> +            'packages/mapper/assets/no_image.png',
Вынести в project-level константу

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/paragraph_block.dart
> +const String monospacedFontFamily = 'RobotoMono';
Почему он публичный и экспортируется вместе с ParagraphBlock?

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/heading_block.dart
> +        color: const Color(0xFF000000),
Как только добавим UI-kit, тут нужно будет импортить ColorScheme из контекста и вставлять текст. Можешь тудушку оставить

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/heading_block.dart
> +        fontSize: 20.0 * model.level,
Аналогично, тут шрифт из темы будет импортиться

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/block.dart
> +final Map<ListType, ListBlock Function(ListBlockModel)> listTypeMap = {
Предпочитай использовать switch-case для такого. Он быстрее и логичнее именно тут 

Например, если у тебя в этот Map добавится новое значение ListType.colored, то ты не заметишь, что не обработала его здесь, потому что он не подсветит

2023-10-24 07:45 UTC, mpkander commented on packages/mapper/lib/src/blocks/block.dart
> +final Map<Type, Block<BlockModel> Function(BlockModel)> modelBlockMap = {
Аналогично, гораздо лучше использовать switch-case. В частности, чтобы не делать постоянное приведение типов

2023-10-24 08:59 UTC, Evgenia-bit commented on packages/mapper/lib/src/blocks/block.dart
> +final Map<Type, Block<BlockModel> Function(BlockModel)> modelBlockMap = {
ты имеешь в виду передавать в switch model.runtimeType и возвращать на основе него нужный Block?

2023-10-30 06:28 UTC, mpkander approved these changes

2023-10-30 06:53 UTC, merged